[build]
  command = "npm ci && npm run build:netlify"
  publish = "dist/demo/browser"

[build.environment]
  NODE_VERSION = "18.19.1"
  NPM_VERSION = "9"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
